### ISSUE TITLE
got get impossible: https://www.fknsrs.biz SSL certificate expired

### ISSUE THREAD

**Issue by siebertm** [deoxxa/hl7#2]
Your SSL certificate is expired and we can't `go get` the library. Can this be fixed please?

**Comment by deoxxa** [comment]
Fixed! Apparently I forgot to restart nginx last time I updated my certificate. Thanks for pointing it out!

**Comment by siebertm** [comment]
That was quick, thank you!

**Comment by levinalex** [comment]
Looks like this happened again
