### ISSUE TITLE
Certificate on fknsrs.biz is for cvm.fknsrs.biz

### ISSUE THREAD

**Issue by garywarner** [deoxxa/hl7#9]
Like so many others, this package is so helpful and has always worked flawlessly for us - thank you.

Unfortunately, the redirection from fknsrs.biz appears to be currently broken because the SSL certificate either doesn't contain a wildcard or doesn't contain a SN for fknsrs.biz. From our build today:
```
unrecognized import path "fknsrs.biz/p/hl7": https fetch: Get "https://fknsrs.biz/p/hl7?go-get=1": x509: certificate is valid for cvm.fknsrs.biz, not fknsrs.biz
```

Checking with a browser at https://fknsrs.biz/p/hl7 gives the same analysis:
> This server could not prove that it is fknsrs.biz; its security certificate is from cvm.fknsrs.biz. This may be caused by a misconfiguration or an attacker intercepting your connection.

I realise this repo isn't under active development - it's solid as it is! But could you perhaps consider looking at this. We'll fork in the meantime and see if we can get it back up for our work. Many thanks again - love the blog that goes with this by the way, it's where I send the young padwans to get their first day training on the joy that is HL7v2.

**Comment by deoxxa** [comment]
Ah! All fixed now, sorry about that.

**Comment by comatrion** [comment]
Hi
I'm seeing a similar error currently in my build
```
fknsrs.biz/p/xml@v0.0.0-20141012122126-75354j641d0d: unrecognized import path "fknsrs.biz/p/xml" (https fetch: Get https://fknsrs.biz/p/xml?go-get=1: dial tcp 212.47.249.51:443: i/o timeout)
```
